### ISSUE TITLE
Netflix Capstone Review

### ISSUE THREAD

**Issue by hmontero1205** [pelian/codeacademy#1]
Overall, your work met the project specifications!! Great work! :)

Your code is very neat and I don't see any issues there.
I think your presentation is very very sleek and professional. Your visualizations are complimented by insightful bodies of texts, a good balance. I will say that one or two of your graphs are a bit too small and could've been bigger. Other than that, awesome stuff! Keep it up.

**Comment by pelian** [comment]
@hmontero1205 Any chance you can also review the unit 3 project. I had a github syncing issue earlier (added unit 3 folder in gitignore). Appreciate it :)
