### ISSUE TITLE
Overall

### ISSUE THREAD

**Issue by Axkaban** [pelian/codeacademy#13]
Grade: **Surpasses requirements and expectations**
A total 200 ok! Congratulations for an amazing work on the Jammming project!

I hope you get to play with `react-router-dom` soon, and I believe you would appreciate to work with redux, here's one of their tutorials to get acquainted with it: [https://redux.js.org/basics](https://redux.js.org/basics)

You are more than ready to tackle the feature request, so best of luck on you future ventures!

**Comment by pelian** [comment]
Really appreciate @Axkaban for the thorough review. I was planning to get familiar with the react-router-dom library and redux next, so getting your feedback was very helpful. Thanks again.
