### ISSUE TITLE
Constellation Project Summary & Rubric Score

### ISSUE THREAD

**Issue by karl-project-review** [pelian/codeacademy#2]
### Criteria 1: Matplotlib and CSV
* _Score Level:_ 4/4 (Exceeds Expectations)
* _Comments:_ You imported the necessary libraries.
### Criteria 2: Implementation of 2D Visualization
* _Score Level:_ 4/4 (Exceeds Expectations)
* _Comments:_ Not only did you create a 2D plot of the constellation, but you also added an appropriate title and gave each star a unique color. Well done!
### Criteria 3: Implementation of 3D Visualization
* _Score Level:_ 4/4 (Exceeds Expectations)
* _Comments:_ You created a rotatable 3D plot of the constellation with an appropriate title and a unique color for each star. Good job!
### Overall Score: 12/12 (Exceeds Expectations)
Great work! You created all of the necessary plots, and used some more advanced syntax in order to make the random colors work. My one recommendation would be to consider using the same color scheme (as in the same static pairings of unique colors for each different star) for both of these plots instead of random colors, though, as this would allow you to easily match the stars from the 2D plot to their counterparts in the 3D plot by color, thereby potentially making the colors more useful. Again, great job!

**Comment by pelian** [comment]
Thank you appreciate the review! @karl-project-review
