### ISSUE TITLE
Tome Rater - Boolean Expressions

### ISSUE THREAD

**Issue by hmontero1205** [pelian/codeacademy#3]
Throughout your program, you have boolean expressions that are correct, but redundant. Here's one:
```
if self.name == other_user.name and self.email == other_user.email:
   return True
return False
```
This if-statement is not necessary at all. Look at what you're doing. You're checking to see if that boolean expression is True or False. If True, return True. If False, return False. Checking the value is unnecessary work. Just return the expression.

`return self.name == other_user.name and self.email == other_user.email`

**Comment by pelian** [comment]
Good point. @hmontero1205
