### ISSUE TITLE
Tome Rater - String formatting using .format()

### ISSUE THREAD

**Issue by hmontero1205** [pelian/codeacademy#4]
Your use of .format() is very readable but in my opinion, unnecessary work.
Let's look at this line:
`'TomeRater has {users} users and {books} books'.format(users=len(self.users), books=len(self.books))`
You don't have to give the variables in the string names, nor do you have to define them inside of the function. Just do this:
`'TomeRater has {} users and {} books'.format(len(self.users), len(self.books))`
You should only give the variables inside the string values if you are not going to use the variables inside of .format() in the order you passed them in.

**Comment by pelian** [comment]
This one... I was a bit confused about in general as there were a number of ways the same string could be outputted from using "+" and variables explicitly, to using % (which I think is a remnant of Python 2) and then the brackets { } empty/name and format. They all seem to be capable of accomplishing the same thing.

Is there some kind of style guide or "generally accepted practices" reference that a company or individual has created for Python 3 that has become the defacto standard for styling?
