### ISSUE TITLE
Project Overview

### ISSUE THREAD

**Issue by hmontero1205** [pelian/codeacademy#5]
## Rubric Score
 
### Criteria 1: Valid Python Code
* _Score Level:_ 4
 
### Criteria 2: Implementation of Project Requirements
* _Score Level:_ 4
 
### Criteria 3: Software Architecture
* _Score Level:_ 4
 
### Criteria 4: Uses Python Language Features
* _Score Level:_ 4
 
### Overall Score: 16/16
Your work definitely meets the project requirements -- awesome work!! My issues were just style/formatting. The actual logic of your program is really great and demonstrates that you have a very strong understanding of the course material. Congrats on finishing the course and best of luck in your future endeavors!

**Comment by pelian** [comment]
Thank you! Appreciate your review. I'll take a dive into looking at your comments to make some improvements. 👍
