### ISSUE TITLE
To start

### ISSUE THREAD

**Issue by Axkaban** [pelian/codeacademy#6]
What a wonderful take on the ol' Jammming project. It is refreshing, completely integrated, and with a great sense of style.

One unrelated thing. I do understand the reasoning to keep one repository for all your Codecademy projects, but it will be cleaner to have each project in its own repository, that way for example, I will not have to clone all your prior projects just to test your Jammming app. The same will apply when you work at any company where the application will have its repository, and you and the team will work in it in different branches.

**Comment by pelian** [comment]
@Axkaban you are totally correct. In hindsight, I really should have separated out these repositories. I signed up for three courses on Code Academy simultaneously and just started working through each one so it ended up with this structure. I will make sure to avoid this for future projects! 👍
